### ISSUE TITLE
cant serve with that pb_hooks

### ISSUE THREAD

**Issue by agaitan026** [burggraf/pb-import#1]
error:

root@server:/pocketbase# ./pocketbase serve --http="0.0.0.0:8090"
Failed to execute import_csv.pb.js:
 - SyntaxError: SyntaxError: (anonymous): Line 1:11 Unexpected token : (and 9 more errors)

**Comment by burggraf** [comment]
Make sure the papaparse file is also in the pb_hooks folder.

**Comment by agaitan026** [comment]
You got it thank you
